# Generated by Django 4.2.17 on 2025-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('arcana', models.CharField(max_length=50)),
                ('suit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='tarotcards/')),
            ],
        ),
    ]
